### ISSUE TITLE
Using AzureOpenAI

### ISSUE THREAD

**Issue by mtelang** [filip-michalsky/SalesGPT#1]
Hello,

Thanks for developing this project. I was trying to run the main file (run.py) giving my API key. It ran into issues stating wrong bearer toekn. I realized, my openai sandbox is on Azure and has a company specific domain. 
So I changed the .env file (providing AzureOpenAI base URL and key).
  os.environ['OPENAI_API_KEY'] = envs_dict['OPENAI_API_KEY']
  os.environ['OPENAI_API_BASE'] = envs_dict['OPENAI_API_BASE']

And also changed the following in run.py

llm = AzureOpenAI(temperature=0)

Now I am getting following error

Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: No connection adapters were found for "'https://mysandboxurl/'\n/engines//completions".

Let me know if this is the right approach and what is going wrong. Thanks.

Madhur

**Comment by filip-michalsky** [comment]
@mtelang thanks for the question! I have big plans with improving this project to be the best open source sales agent out there and so happy someone is using it.

i think your issue stems from a proxy / corporate firewall issue. Can you interact with the OpenAI endpoints directly using your keys in your sandbox? Please test that and let me know.

**Comment by mtelang** [comment]
@filip-michalsky - I do not have access to the sandbox, I can only leverage the API-key to make calls. But if this answers your question, this is not the my first implementation of llm, I have used agents and tools of LangChain and the OpenAI endpoints were executed successfully. This is the first time I am getting such issues. The only difference is, this project is completely built on OpenAI and I have Azure sandbox (atleast this is what I think, happy to get your thoughts). 

Looking the the prompt template. I was very excited to get this up and running : )

**Comment by filip-michalsky** [comment]
@mtelang  I am a bit confused what you mean you "don't have access to the sandbox but can use your API key to make calls.

Does the following help to do the config to execute `run.py`?
https://python.langchain.com/en/latest/modules/models/llms/integrations/azure_openai_example.html

**Comment by filip-michalsky** [comment]
@mtelang any update? I will close the issue if not.
