### ISSUE TITLE
Make it call you

### ISSUE THREAD

**Issue by Gamma-Software** [filip-michalsky/SalesGPT#11]
@filip-michalsky any chance to know how you implemented your demonstration when your SalesGPT is calling ?

**Comment by filip-michalsky** [comment]
@Gamma-Software The calling functionality will be available via an API - stay tuned!

**Comment by filip-michalsky** [comment]
@Gamma-Software The calling functionality will be available via an API - stay tuned!

**Comment by lansheng919** [comment]
Hi @filip-michalsky , kindly follow up on the calling functionality. Thanks!
