### ISSUE TITLE
underfined

### ISSUE THREAD

**Issue by therealtimex** [filip-michalsky/SalesGPT#136]
I encounter this error  
<img width="1380" alt="Screenshot 2024-04-05 at 22 30 44" src="https://github.com/filip-michalsky/SalesGPT/assets/154565560/deea13d8-f40a-45fb-96c1-89244677b2d2">

**Comment by chemik-bit** [comment]
Hey @therealtimex, sorry for the issue. We have hopefully fixed the issue. If you encounter any other issue please let us know again! Thanks!
