### ISSUE TITLE
Have you considered the agent's use of streaming?

### ISSUE THREAD

**Issue by zandko** [filip-michalsky/SalesGPT#140]
Currently, it appears that the agent supports streaming, but there may be a need to make some changes in terms of prompt and string parsing.

![IMG-2024-04-08-15 27 20@2x](https://github.com/filip-michalsky/SalesGPT/assets/37948383/1501b619-e8d6-4411-9f4f-9330c66b71a5)

**Comment by chemik-bit** [comment]
Hi @zandko, thank you for your message! We are currently working on numerous improvements, however didn't plan to focus too much on this, What sort of prompt and string parsing improvements would you suggest?
