### ISSUE TITLE
No response in front end page

### ISSUE THREAD

**Issue by murphyren225** [filip-michalsky/SalesGPT#142]
I hope to run front end interface by command: npm run dev and also run backend command uvicorn run_api:app --port 8000. Seems nothing returned like below. how do i know the error log? 
![Screenshot 2024-04-14 at 10 31 29 AM](https://github.com/filip-michalsky/SalesGPT/assets/133839187/f0a75b9a-79ab-4fa4-a97d-cb73f6446946)

**Comment by chemik-bit** [comment]
Hi @murphyren225, thank you for your message and bringing this to our attention, we think we have already fixed the issue. If you encounter any other issue please let us know!
