### ISSUE TITLE
Question not issue. Plans to add the actual demos to this repo

### ISSUE THREAD

**Issue by mynumu** [filip-michalsky/SalesGPT#148]
Hey

Great work. Any plans to actually release the code that you use for all  your cool demos on the main repo page here?

The repo doesn’t have any phone calling or active code for the examples you use like the patient intake or stripe payments..

If you only want to sell the phone calling as a service can you confirm 

thanks

**Comment by chemik-bit** [comment]
Hey @mynumu, most of the code we use for our demos is based on the code in this repo, however it is true we also have a closed-source version we offer as a service. We plan on gradually adding to the SalesGPT repository, however the amount we will publish here will always be slightly behind the closed-source version. Does this answer your question? Btw stripe payments are already available with SalesGPT.
