### ISSUE TITLE
Do I need to use a tool? No

### ISSUE THREAD

**Issue by anushaharish538** [filip-michalsky/SalesGPT#154]
Hi,

For every question I type I'm getting Do I need to use a tool? No. Always same "Do I need to use a tool? No"

**Comment by chemik-bit** [comment]
Hi @anushaharish538 SalesGPT has various "Tools" it uses to satisfy the current requirements of the client. Some of the current tools are generating a payment link, sending an email etc. If you have a basic interaction with SalesGPT you might not need them, but SalesGPT tries to figure out whether it will need them or not and informs you of its decision. Does this make sense?

**Comment by chemik-bit** [comment]
Hey @anushaharish538, the likely issue is the ENVIRONMENT environment variable, which we have had to rename for production purposes to NEXT_PUBLIC_ENVIRONMENT, which I can however see hasn't been implemented in the most up to date version. Hopefully this does the trick for you!
