### ISSUE TITLE
How to support more other LLM models?

### ISSUE THREAD

**Issue by VersaceP** [filip-michalsky/SalesGPT#20]

**Comment by filip-michalsky** [comment]
@VersaceP since we are using `langchain` the LLM model is abstracted.

you should be able to update the LLM like so:

```
# from langchain.chat_models import ChatOpenAI # replace this
from langchain.chat_models import ChatAnthropic # new

... rest of code
```

Let me know if this works for you?

**Comment by filip-michalsky** [comment]
@VersaceP  is your issue solved now? I will close this by end of week if no response.

**Comment by VersaceP** [comment]
I find out where to update. Thx.

**Comment by filip-michalsky** [comment]
@VersaceP this is solved with latest PR!
