### ISSUE TITLE
Inconsistent Handling of kwargs Boolean Values

### ISSUE THREAD

**Issue by cwazuidema** [filip-michalsky/SalesGPT#29]
**Description:**

The agents.py file currently employs varying methods to handle boolean values in kwargs. For instance, it checks "use_custom_prompt" as a string, whereas "use_tools" is treated as a boolean. Such inconsistency may lead to confusion and unexpected behaviors.

I propose that both cases be managed in a consistent manner by treating "True" values as strings. Doing so will make the codebase follow a unified strategy for handling these options.

Below is my updated example_agent_setup.json. Please pay attention to the last two kwargs (use_tools and product_catalog), and note that we don't use JSON true but the string "True" for boolean values.

```
{
"salesperson_name": "Ted Lasso",
"salesperson_role": "Business Dev Rep",
"company_name": "Sleep Haven",
"company_business": "Sleep Haven offers premium mattresses and sleep accessories for ultimate comfort...",
"company_values": "Sleep Haven aims to enhance sleep quality through top-notch products and service...",
"conversation_purpose": "Discover sleep needs, offer premier mattress solution.",
"conversation_type": "call",
"use_custom_prompt": "True",
"custom_prompt": "Remember, you're {salesperson_name}, a {salesperson_role} at {company_name}...",
"use_tools": "True",
"product_catalog": "examples/sample_product_catalog.txt"
}
```

Currently, different methods are used to handle boolean values in kwargs, as mentioned earlier. This divergence can lead to ambiguity and unforeseen behavior.

I recommend that we adopt a uniform method by treating "True" values as strings. This will bring consistency to the codebase's handling of these options.

**Proposed Fix:**

Update the following section in agents.py:

_Current code:_

```
if "use_tools" in kwargs.keys() and kwargs["use_tools"] is True:
```

_Updated code:_
```
if "use_tools" in kwargs and kwargs["use_tools"] == "True":
```

**Steps to Reproduce:**

Use my example_agent_setup.json.
Observe that tools are never added.

**Expected Behavior:**

The code should manage boolean values in kwargs uniformly by recognizing "True" values as strings.

**Comment by filip-michalsky** [comment]
@cwazuidema thanks so much for flagging, this bug has been fixed, will treat `"use_tools"` as `string` to be consistent when loading from a JSON file.
