### ISSUE TITLE
Hello, when will this version be normal? I just cloned and reported an error.

### ISSUE THREAD

**Issue by luolin-ai** [filip-michalsky/SalesGPT#33]
Hello, when will this version be normal? I just cloned and reported an error.
`Traceback (most recent call last):
  File "F:\GitHub\Llama2-Chinese\SalesGPT\run.py", line 6, in <module>
    from salesgpt.agents import SalesGPT
  File "F:\GitHub\Llama2-Chinese\SalesGPT\salesgpt\agents.py", line 25, in <module>
    class SalesGPT(Chain, BaseModel):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by filip-michalsky** [comment]
@luolin-ai can you please share your platform and library versions in `requirements.txt` so that we can see if we can reproduce your issue?

I don't use windows but it appears you do - do you have the latest libraries installed?

**Comment by luolin-ai** [comment]
ok Ok, thank you, it has been solved, and there is another problem I want to add functions, one is to change the docking database

**Comment by filip-michalsky** [comment]
@luolin-ai please open a separate issue for this new problem, thank you!
