### ISSUE TITLE
python run.py  error

### ISSUE THREAD

**Issue by MSYXing** [filip-michalsky/SalesGPT#42]
from langchain.llms.base import create_base_retry_decorator
ImportError: cannot import name 'create_base_retry_decorator' from 'langchain.llms.base'

**Comment by filip-michalsky** [comment]
@MSYXing thanks for raising this issue. 

Can you please give us library versions of langchain, python version, your OS and what command you were executing?

Looks like you are using older version of langchain

**Comment by filip-michalsky** [comment]
@MSYXing just re-surfacing this, will close this issue if I don't get your response within the next week. Thanks.

**Comment by chemik-bit** [comment]
Hopefully your issue has been solved with new our improved dependency management, if not, please create a new issue

**Comment by paresh795** [comment]
I am facing this issue, Followed all the steps for installation and got this : 

"    from langchain.llms.base import create_base_retry_decorator
ImportError: cannot import name 'create_base_retry_decorator' from 'langchain.llms.base'"

**Comment by atomsi** [comment]
same issue during run "python run.py --verbose True --config examples/example_agent_setup.json"
and the langchain is 0.1.3 :
![image](https://github.com/filip-michalsky/SalesGPT/assets/4404196/90f24806-997b-4b4b-9111-05d8071987fa)

**Comment by ZuzooVn** [comment]
> same issue during run "python run.py --verbose True --config examples/example_agent_setup.json" and the langchain is 0.1.3 : ![image](https://private-user-images.githubusercontent.com/4404196/300144285-90f24806-997b-4b4b-9111-05d8071987fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjc0MzEsIm5iZiI6MTcwNjM2NzEzMSwicGF0aCI6Ii80NDA0MTk2LzMwMDE0NDI4NS05MGYyNDgwNi05OTdiLTRiNGItOTExMS0wNWQ4MDcxOTg3ZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTQ1MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVmY2MwZmY0YjYyMzZjMzY3ZTUzYjNjZTU1NWJlZmNkZTgwMThiNGQ5MjZlNWMxOTVmODYzYTBkM2Q2OWM1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dl1fXE8KqE_N1WVbqmhHQRnyMVc9ewJ8iRz8olJjYKs)

please check this: https://github.com/filip-michalsky/SalesGPT/issues/89
