### ISSUE TITLE
sales_agent_executor is none

### ISSUE THREAD

**Issue by muhammadhasnain100** [filip-michalsky/SalesGPT#43]
I encountered an issue within this GitHub repository that required resolution. Despite attempting various solutions and consulting the official Langchain website, I was able to address the problem. The source of the issue was identified as the "agent.py" file. Specifically, the line of code "sales_agent_executor: Union[AgentExecutor, None] = Field(...)" resulted in a "sales_agent_executor" being returned as "None". Your assistance in resolving this matter would be greatly appreciated.

Moreover, the error message "AttributeError: 'NoneType' object has no attribute 'run'" was encountered in this context.

**Comment by filip-michalsky** [comment]
@muhammadhasnain100 thanks a lot for creating the issue!

 Can you please describe the steps you took to get this error so that we can reproduce it?

‘sales_agent_executor’ is supposed to be None if use_tools!=“True” (using string type cast to be consistent when using JSON agent config)

**Comment by muhammadhasnain100** [comment]
The issue has been successfully resolved. We greatly appreciate your assistance.

**Comment by filip-michalsky** [comment]
Resolved.
