### ISSUE TITLE
run.py 中没有决定对话阶段的部分

### ISSUE THREAD

**Issue by pandaupc** [filip-michalsky/SalesGPT#53]
run.py 中没有决定对话阶段的部分是为什么呢？

**Comment by janewu77** [comment]
应该是不需要了。 现在是在整在一个prompt里面达成了。

**Comment by chemik-bit** [comment]
Thank you @janewu77 for your response. @pandaupc Hope this answers your question. If not, please create a new issue or contact me, @janewu77 or @filip-michalsky.
