### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by Shaon2221** [filip-michalsky/SalesGPT#56]
```TypeError                                 Traceback (most recent call last)
SalesGPT-main\examples\sales_agent_with_context.ipynb Cell 23 line 1
---->[1] class SalesGPT(Chain, BaseModel):
         [2] """Controller model for the Sales Agent."""
         [4]conversation_history: List[str] = []

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
I don't know what is wrong with given example code in "sales_agent_with_context.ipynb". I am getting this error. looking forward to get help from the community. Please note that, I haven't change anything in code but getting this error.

**Comment by RizkiNoor16** [comment]
@Shaon2221 i think there is a bug with Pydantic version. I'm using Pydantic==1.10.7  to resolve this issue

**Comment by Shaon2221** [comment]
@RizkiNoor16 yeah, You're right mate. This version change worked for me. Thanks for your help. I am grateful to you.
