### ISSUE TITLE
Error in sales_agent_with_context when running stage_analyzer_chain

### ISSUE THREAD

**Issue by Badrul-Goomblepop** [filip-michalsky/SalesGPT#7]
I keep getting the errror message below when I am going through the [Sales GPT with context tutorial](https://github.com/filip-michalsky/SalesGPT/blob/main/sales_agent_with_context.ipynb) and get to the `stage_analyzer_chain.run(conversation_history='')` step:

```
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised APIError: The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID b647982210c2d50cc01ba890f9bfe6f2 in your message.) {
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID b647982210c2d50cc01ba890f9bfe6f2 in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID b647982210c2d50cc01ba890f9bfe6f2 in your message.)', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Tue, 23 May 2023 12:13:13 GMT', 'Content-Type': 'application/json', 'Content-Length': '366', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-processing-ms': '157', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3500', 'x-ratelimit-limit-tokens': '90000', 'x-ratelimit-remaining-requests': '3499', 'x-ratelimit-remaining-tokens': '89427', 'x-ratelimit-reset-requests': '17ms', 'x-ratelimit-reset-tokens': '382ms', 'x-request-id': 'b647982210c2d50cc01ba890f9bfe6f2', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '7cbd362beb98dd82-LHR', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'}.
```

I have confirmed that my OpenAI API key is correct and active.

Also - is the Quick start meant to replace this tutorial? I preferred this one as it gave me more control of the sausage making. I couldn't tell if the QuickStart allowed me to do the same.

**Comment by filip-michalsky** [comment]
@Badrul-Goomblepop looks like this is an API-error, OpenAI SLAs are not robust yet and their servers are down sometimes.

Can you confirm this works for you?

`curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "text-davinci-003",
    "prompt": "Say this is a test",
    "max_tokens": 7,
    "temperature": 0
  }'
`

**Comment by filip-michalsky** [comment]
@Badrul-Goomblepop As far as `quickstart.py` goes, that's meant to just run a quick example of how SalesGPT works, the notebook is better for customization, prompt engineering, etc.

**Comment by Badrul-Goomblepop** [comment]
@filip-michalsky I got the following (note I'm using this on Windows PowerShell though that shouldn't matter)

```
curl https://api.openai.com/v1/completions -H "Content-Type: application/json" -H "Authorization: Bearer MY_API_KEY_HERE" -d '{"model": "text-davinci-003","prompt": "Say this is a test","max_tokens": 7,"temperature": 0}'
{
  "error": {
    "message": "The server had an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 16e3e2e6c0a7e94ebbc89b2db900f23c in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
```

**Comment by filip-michalsky** [comment]
@Badrul-Goomblepop Sorry I missed this. These errors have to do with OpenAI / your proxy configuration, nothing with SalesGPT. The OpenAI servers might have been down at that time 3 weeks ago. Is it working for you now if you retry?

**Comment by filip-michalsky** [comment]
@Badrul-Goomblepop did you retry this?

**Comment by filip-michalsky** [comment]
@Badrul-Goomblepop closing the issue soon as this is not related to SalesGPT but rather to API rate limiting errors coming from the underlying LLM provider.

**Comment by Badrul-Goomblepop** [comment]
@filip-michalsky Sorry for not replying. I can confirm that I ran the tutorial again and I am not having issues now.
